---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "piwik" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
  selector:
    k8s-app: {{ template "fullname" . }}
